#!/bin/bash

# $1で指定されたディレクトリの構造を$2へコピーする


show_usage() {
    echo "使用法： ${0##*/} 参照元ディレクトリ 構造コピー先ディレクトリ"
    echo
    echo "引数で指定された参照元のディレクトリ構造をコピー先のディレクトリへコピーします。"
    echo "コピー先に既存のディレクトリは削除しません。存在していないものが追加されます。"
}

# 引数個数のチェック
if [ $# -ne 2 ]
then
    echo
    echo "引数の個数が異なります。"
    echo
    show_usage

    exit 1
fi

# 引数がディレクトリであるかチェック
if [ ! -d "$1" ]
then
    echo
    echo "最初の引数は参照元のディレクトリを指定してください。"
    echo
    show_usage

    exit 2
fi

if [ ! -d "$2" ]
then
    echo
    echo "２つ目の引数は構造コピー先のディレクトリを指定してください。"
    echo
    show_usage

    exit 3
fi

# 末尾の/を削除する
source_dir="${1%/}"
distnation_dir="${2%/}"

# ディレクトリ構造コピー
find "$1" -type d | awk -v src="${source_dir}" -v dist="${distnation_dir}" -e '
{
    gsub(src, dist);
    print "mkdir -p", $0;
    print "echo", $0, "ディレクトリ生成"
}
' | bash

echo "$2に$1のディレクトリ構造を合わせました。"
