#!/bin/bash

# $1のディレクトリ中のdocumentation.mdから、index.mdを作成する

show_usage() {
    echo "使用法： ${0##*/} 対象ディレクトリ"
    echo
    echo "documentation.mdファイルから、index.mdファイルを生成します。"
}

# 引数個数のチェック

if [ $# -ne 1 ]
then
    echo
    echo "引数の個数が異なります。"
    echo
    show_usage

    exit 1
fi

# 引数がディレクトリであるかチェック

if [ ! -d "$1" ]
then
    echo
    echo "最初の引数に、変換するファイルの存在するディレクトリを指定してください。"
    echo
    show_usage

    exit 2
fi

# 存在していれば末尾の/を削除する
dir="${1%/}"

# ja|en部分を削除
tmp="${dir%/*}"

# 先頭のディレクトリ部分を削除
ver="${tmp##*/}"

awk -v ver="${ver}" -v dir="${dir}" -f 'scripts/awk/documentation2index.awk' "${dir}/documentation.md" > "${dir}/index.md"

echo "${dir}/documentation.mdから、${dir}/index.mdを生成"
