#!/bin/bash

# jaとenディレクトリでhtmlを生成する時に使用する、layout.htmlファイルを生成する

# $1 出力対象のlayout.html
# $2 ヘッダーファイル
# $3 フッターファイル
# $4 章のアイテムを作成するための、documentation.md
# $5 追加の章アイテム（言語ファイル分） オプショナル

show_usage() {
    echo "使用法： ${0##*/} layout.htmlパス ヘッダーファイル フッターファイル documentation.mdパス"
}

if [ "${4}" = "none" ]
then
    # ディレクトリ用のテンプレートから生成
    awk -f scripts/awk/generate-doc-layout.awk -v header_file="${2}" -v footer_file="${3}" -v doc_file="${4}"  templates/base-directory-template.html > "${1}"
else
    # ドキュメント用のテンプレートから生成
    awk -f scripts/awk/generate-doc-layout.awk -v header_file="${2}" -v footer_file="${3}" -v doc_file="${4}" -v append_file="${5}"  templates/base-template.html > "${1}"
fi

echo "テンプレート生成：${1}"
